queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build

pull_request_rules:
  - name: Automatic merge on approval and successful build
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
    actions:
      queue:
        method: squash
        name: default
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
