name: inputs-workflow-lab
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'True to print to STDOUT'
        required: true
        type: string
permissions:
  contents: read
  actions: write
  
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
      - name: trigger another workflow
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/neilkuan/workflow-test/actions/workflows/docker-run.yaml/dispatches \
          -d '{"ref":"main"}'
